### ISSUE TITLE
是否可以增加py3支持

### ISSUE THREAD

**Issue by MyFaith** [littlecodersh/NetEaseMusicApi#1]
Traceback (most recent call last):
  File "/Users/Faith/Documents/projects/testing/test.py", line 3, in <module>
    import NetEaseMusicApi
  File "/Users/Faith/Documents/projects/venv3/lib/python3.5/site-packages/NetEaseMusicApi/**init**.py", line 1, in <module>
    from RawApi import *
ImportError: No module named 'RawApi'

on Python3.5.1

**Comment by littlecodersh** [comment]
@MyFaith 目前只兼容python 2.7，不过对于兼容python 3应该也不用太多修改

**Comment by MyFaith** [comment]
可以修改一下吗？我试着修改后，还是会出现这个问题。

**Comment by littlecodersh** [comment]
@MyFaith 已经完成了py3支持
